version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kt3k/saku
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          key: v1
      - run: cd pkg/saku; go test -tags coverage -coverprofile=coverage.txt -covermode=atomic .
      - save_cache:
          key: v1
          paths:
            - "/go/pkg"
      - run: bash <(curl -s https://codecov.io/bash)
